#!/usr/bin/env python3
"""
The public lobby directory.

A phone book, not a game server. Rooms announce themselves here and are
listed for anyone browsing; the game itself never touches this service.
Players still connect peer to peer, the host still owns the only real game
state, and every private room code works exactly as before. If this process
is down, the public list is empty and nothing else changes - which is the
property worth protecting, because it is the one that keeps the project's
claim about having no backend honest in the part that matters.

Nothing is persisted. A room exists here only while it keeps saying so:
announce on open, beat every 20 seconds, and vanish 45 seconds after the
host stops - which is also what happens when a browser tab is closed
without warning, so there is no separate cleanup path to get wrong.

Binds 127.0.0.1; nginx puts it on the internet at /lobbies/.
Python 3 standard library only, same as the status panel.
"""
from __future__ import annotations

import json
import re
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

HOST, PORT = "127.0.0.1", 9100

TTL = 45.0                # a room is live this long after its last beat
MAX_ROOMS = 300           # global ceiling; the list is not a database
MAX_PER_IP = 4            # one person hosting a few tables, not a spammer
ANNOUNCE_PER_MIN = 40     # per IP, across all rooms

# The room code is the host's peer id, and it is generated by the client from
# a fixed word list: WORD-WORD-NN. Anything else is not a room code.
ROOM_RE = re.compile(r"^[A-Z]{3,10}-[A-Z]{3,10}-\d{1,3}$")
# Must match the ids in src/game/settings.ts; anything else is "custom".
PRESETS = {"classic", "speed", "friendly", "tycoon", "custom"}

_lock = threading.Lock()
_rooms: dict[str, dict] = {}
_hits: dict[str, list[float]] = {}


def clean_text(value: object, limit: int) -> str:
    """Length-capped, control characters removed. The client renders these as
    text so escaping is React's job, but nothing stops a listing from being
    a screenful of newlines unless it is stopped here."""
    text = str(value or "")
    text = "".join(ch for ch in text if ch.isprintable())
    return text.strip()[:limit]


def rate_ok(ip: str) -> bool:
    now = time.time()
    hits = [t for t in _hits.get(ip, []) if now - t < 60]
    hits.append(now)
    _hits[ip] = hits
    if len(_hits) > 4000:                      # keep the table bounded
        for k in [k for k, v in _hits.items() if not v or now - v[-1] > 300]:
            _hits.pop(k, None)
    return len(hits) <= ANNOUNCE_PER_MIN


def live_rooms() -> list[dict]:
    now = time.time()
    out = []
    for room in list(_rooms.values()):
        if now - room["seen"] > TTL:
            _rooms.pop(room["id"], None)
            continue
        out.append({
            "id": room["id"],
            "host": room["host"],
            "seats": room["seats"],
            "maxSeats": room["maxSeats"],
            "preset": room["preset"],
            "deviations": room["deviations"],
            "age": int(now - room["opened"]),
        })
    # Joinable first, then the ones with people already in them, then newest:
    # a full room is not an option and an empty one is a worse bet than a
    # table that already has three players waiting.
    out.sort(key=lambda r: (r["seats"] >= r["maxSeats"], -r["seats"], r["age"]))
    return out


class Handler(BaseHTTPRequestHandler):
    server_version = "lobbies/1"

    # -- plumbing ----------------------------------------------------------
    def _cors(self):
        # The game is served from two places - the droplet and GitHub Pages -
        # and both should be able to see the same list.
        origin = self.headers.get("Origin", "")
        if re.fullmatch(r"https://(aytingchi\.uz|www\.aytingchi\.uz|[a-z0-9-]+\.github\.io)"
                        r"|http://localhost:\d+", origin or ""):
            self.send_header("Access-Control-Allow-Origin", origin)
            self.send_header("Vary", "Origin")

    def _send(self, code: int, payload: object):
        body = json.dumps(payload).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self._cors()
        self.end_headers()
        self.wfile.write(body)

    @property
    def client_ip(self) -> str:
        # nginx is the only thing in front of this, and it sets this header.
        return (self.headers.get("X-Real-IP") or self.client_address[0] or "?")[:45]

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.send_header("Access-Control-Max-Age", "600")
        self._cors()
        self.end_headers()

    # -- routes ------------------------------------------------------------
    def do_GET(self):
        if self.path.rstrip("/").endswith("/rooms"):
            with _lock:
                return self._send(200, {"rooms": live_rooms()})
        return self._send(404, {"error": "not found"})

    def do_POST(self):
        path = self.path.rstrip("/")
        length = min(int(self.headers.get("Content-Length") or 0), 2048)
        try:
            body = json.loads(self.rfile.read(length) or b"{}")
        except Exception:
            return self._send(400, {"error": "bad json"})
        if not isinstance(body, dict):
            return self._send(400, {"error": "bad body"})

        room_id = clean_text(body.get("id"), 40).upper()
        if not ROOM_RE.fullmatch(room_id):
            return self._send(400, {"error": "bad room id"})

        if path.endswith("/close"):
            with _lock:
                _rooms.pop(room_id, None)
            return self._send(200, {"ok": True})

        if not path.endswith("/announce"):
            return self._send(404, {"error": "not found"})

        ip = self.client_ip
        with _lock:
            if not rate_ok(ip):
                return self._send(429, {"error": "slow down"})

            existing = _rooms.get(room_id)
            if existing is None:
                if len(_rooms) >= MAX_ROOMS:
                    return self._send(503, {"error": "directory full"})
                mine = sum(1 for r in _rooms.values() if r["ip"] == ip)
                if mine >= MAX_PER_IP:
                    return self._send(429, {"error": "too many rooms"})

            try:
                seats = max(0, min(8, int(body.get("seats", 0))))
                max_seats = max(2, min(8, int(body.get("maxSeats", 6))))
                deviations = max(0, min(30, int(body.get("deviations", 0))))
            except (TypeError, ValueError):
                return self._send(400, {"error": "bad numbers"})

            preset = clean_text(body.get("preset"), 12).lower()
            if preset not in PRESETS:
                preset = "custom"

            now = time.time()
            _rooms[room_id] = {
                "id": room_id,
                "host": clean_text(body.get("host"), 18) or "Someone",
                "seats": seats,
                "maxSeats": max_seats,
                "preset": preset,
                "deviations": deviations,
                "ip": ip,
                "seen": now,
                "opened": existing["opened"] if existing else now,
            }
        return self._send(200, {"ok": True, "ttl": int(TTL)})

    def log_message(self, *_):
        pass


if __name__ == "__main__":
    ThreadingHTTPServer.allow_reuse_address = True
    ThreadingHTTPServer((HOST, PORT), Handler).serve_forever()
