#!/usr/bin/env python3
"""
The public lobby directory, and the table log the operator's panel reads.

Two jobs, kept apart.

The directory is a phone book, not a game server. Public rooms announce
themselves here and are listed for anyone browsing; the game itself never
touches this service. Players still connect peer to peer, the host still
owns the only real game state, and every private room code works exactly as
before. If this process is down, the public list is empty and nothing else
changes.

The table log is for the operator. Whoever runs a table - a room's host, or
the browser a solo game lives in - reports what it looks like: the game,
the seats and who is in them, whether it has started, whose turn it is, who
won. Those reports are kept live in memory and every change of shape
(opened, started, joined, dropped, finished, closed) is appended to a
day file, so the panel can answer "who is playing right now" and "what
happened today". It is never read back by the game, and it is never public:
nothing here serves it over HTTP. The panel reads the files directly.

A table exists here only while it keeps saying so: a report on every change
and a beat every 20 seconds. One that falls quiet for 90 seconds - a closed
tab, a lost connection - is closed as "went quiet", with no separate cleanup
path to get wrong. One that comes back soon after (a refresh, a host handing
over) picks up where it was rather than counting as a new table.

It also enforces the operator's moderation. The panel writes bans.json next
to the table log (who may not play, which room codes are closed); this
service reads it back every few seconds. A banned host's room never reaches
the public list, and the answer to its announce says so. A report's answer
carries what the reporting browser can act on: which seated accounts are
banned (so the host's client removes them), whether its own host is banned,
whether the room code was closed. Reports themselves are never refused -
the panel staying able to see a table matters more than turning it away.

Binds 127.0.0.1; nginx puts it on the internet at /lobbies/.
Python 3 standard library only, same as the status panel.
"""
from __future__ import annotations

import json
import os
import re
import threading
import time
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

HOST, PORT = "127.0.0.1", int(os.environ.get("LOBBIES_PORT", "9100"))

# ---------------------------------------------------------------- directory --

TTL = 90.0                # a room is live this long after its last beat; a
                          # hidden tab's timers can slow to one a minute
MAX_AGE = 3 * 3600.0      # however often it beats, a room this old is done:
                          # an open tab nobody is at is not a table to join
MAX_ROOMS = 300           # global ceiling; the list is not a database
MAX_PER_IP = 4            # one person hosting a few tables, not a spammer
ANNOUNCE_PER_MIN = 40     # per IP, across all rooms
# nginx splits 443 by TLS name and passes the stream through, so every
# request arrives from 127.0.0.1. A per-IP limit on that address is a limit
# on everyone at once - it capped the whole site at four public rooms - so
# loopback falls back to these site-wide numbers instead.
GLOBAL_ANNOUNCE_PER_MIN = 900

# The room code is the host's peer id, and it is generated by the client from
# a fixed word list: WORD-WORD-NN. Anything else is not a room code.
ROOM_RE = re.compile(r"^[A-Z]{3,10}-[A-Z]{3,10}-\d{1,3}$")
# Must match the ids in src/game/settings.ts; anything else is "custom".
PRESETS = {"classic", "speed", "friendly", "dealmaker", "tycoon", "custom"}

# -------------------------------------------------------------- table log --

STATE_DIR = os.environ.get("LOBBIES_STATE", "/var/lib/lobbies")
TABLE_TTL = 90.0          # a hidden tab's timers can slow to one a minute
REVIVE_WINDOW = 3600.0    # a table back within the hour is the same table
MAX_TABLES = 500
RECENT_KEEP = 200
REPORT_MIN_GAP = 2.0      # per table
GLOBAL_REPORTS_PER_MIN = 3000
RETAIN_DAYS = 30
SAMPLE_EVERY = 300.0      # one "how many are playing" point per 5 minutes
WRITE_EVERY = 5.0

# A room code, or the id a solo game makes up for itself.
TABLE_RE = re.compile(r"^(?:[A-Z]{3,10}-[A-Z]{3,10}-\d{1,3}|SOLO-[A-Z0-9]{6,12})$")
KINDS = {"monopoly", "cashflow"}
MODES = {"public", "private", "solo"}
PHASES = {"lobby", "playing", "over"}
COLOR_RE = re.compile(r"^#[0-9a-fA-F]{3,8}$")

_lock = threading.Lock()
_io_lock = threading.Lock()
_rooms: dict[str, dict] = {}
_hits: dict[str, list[float]] = {}
_tables: dict[str, dict] = {}
_recent: list[dict] = []          # ended tables, newest first
_dirty = True


def clean_text(value: object, limit: int) -> str:
    """Length-capped, control characters removed. The client renders these as
    text so escaping is React's job, but nothing stops a listing from being
    a screenful of newlines unless it is stopped here."""
    text = str(value or "")
    text = "".join(ch for ch in text if ch.isprintable())
    return text.strip()[:limit]


def clean_int(value: object, lo: int, hi: int) -> int:
    try:
        return max(lo, min(hi, int(value)))
    except (TypeError, ValueError):
        return 0


def is_loopback(ip: str) -> bool:
    return ip in ("127.0.0.1", "::1", "?", "")


def rate_ok(key: str, limit: int) -> bool:
    now = time.time()
    hits = [t for t in _hits.get(key, []) if now - t < 60]
    hits.append(now)
    _hits[key] = hits
    if len(_hits) > 4000:                      # keep the table bounded
        for k in [k for k, v in _hits.items() if not v or now - v[-1] > 300]:
            _hits.pop(k, None)
    return len(hits) <= limit


def live_rooms() -> list[dict]:
    now = time.time()
    out = []
    for room in list(_rooms.values()):
        if now - room["seen"] > TTL or now - room["opened"] > MAX_AGE:
            _rooms.pop(room["id"], None)
            continue
        out.append({
            "id": room["id"],
            "host": room["host"],
            "seats": room["seats"],
            "maxSeats": room["maxSeats"],
            "preset": room["preset"],
            "deviations": room["deviations"],
            "age": int(now - room["opened"]),
            "inProgress": room.get("inProgress", False),
            "openSeats": room.get("openSeats", 0),
            "round": room.get("round", 0),
        })
    # Lobbies with room first, then games with a bot seat to take, then the
    # rest: a full room is not an option, and an empty one is a worse bet than
    # a table that already has three players waiting.
    out.sort(key=lambda r: (
        r["inProgress"],
        (not r["inProgress"]) and r["seats"] >= r["maxSeats"],
        -r["seats"], r["age"],
    ))
    return out


# -------------------------------------------------------------- moderation --
# bans.json is written by the operator's panel (ops/panel.py) into the same
# state directory. It names accounts (u_...) and display names that may not
# play, and room codes that were closed. Read back here at most every few
# seconds; missing or unreadable means no bans, never a failure to serve.

CLOSE_TTL = 24 * 3600.0     # a closed room code stays blocked for a day
_bans_cache: tuple[float, dict] = (0.0, {})


def bans_data() -> dict:
    global _bans_cache
    at, data = _bans_cache
    now = time.time()
    if now - at < 5.0:
        return data
    try:
        with open(os.path.join(STATE_DIR, "bans.json"), encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        data = {}
    if not isinstance(data, dict):
        data = {}
    _bans_cache = (now, data)
    return data


def _bans() -> list:
    bans = bans_data().get("bans", [])
    return [b for b in bans if isinstance(b, dict)] if isinstance(bans, list) else []


def name_banned(name: str) -> bool:
    low = str(name or "").strip().lower()
    return bool(low) and any(b.get("kind") == "name" and b.get("id") == low for b in _bans())


def account_banned(uid: str) -> bool:
    return any(b.get("kind") == "account" and b.get("id") == uid for b in _bans())


def room_closed(room_id: str) -> bool:
    closed = bans_data().get("closed", {})
    at = closed.get(room_id) if isinstance(closed, dict) else None
    return isinstance(at, (int, float)) and time.time() - at < CLOSE_TTL


def moderation_for(table_id: str, report: dict) -> dict:
    """What the reporting browser has to act on: the banned accounts seated
    (its client removes them), whether its own host is banned (its client
    disbands the table), whether the room code was closed (it stops
    announcing). A guest's *name* is never matched for a kick - names are
    claimed, not owned, so only the host's name carries that consequence."""
    out: dict = {}
    seats = [p["id"] for p in report["players"]
             if not p["bot"] and p["id"].startswith("u_") and account_banned(p["id"])]
    if seats:
        out["bannedSeats"] = seats
    host = next((p for p in report["players"] if p["host"]), None)
    if host and (account_banned(host["id"]) or name_banned(host["name"])):
        out["banned"] = True
    if room_closed(table_id):
        out["close"] = True
    return out


# ------------------------------------------------------------- table log --

def clean_player(p: object) -> dict | None:
    if not isinstance(p, dict):
        return None
    color = clean_text(p.get("color"), 9)
    return {
        "id": clean_text(p.get("id"), 24),
        "name": clean_text(p.get("name"), 18) or "?",
        "color": color if COLOR_RE.fullmatch(color) else "#888888",
        "token": clean_text(p.get("token"), 16),
        "bot": bool(p.get("bot")),
        "host": bool(p.get("host")),
        "connected": bool(p.get("connected", True)),
        "cash": clean_int(p.get("cash"), -10**9, 10**9),
        "worth": clean_int(p.get("worth"), -10**9, 10**9),
        "out": bool(p.get("out")),
        "track": clean_text(p.get("track"), 8),
    }


def clean_report(body: dict) -> dict | None:
    kind = clean_text(body.get("kind"), 10)
    mode = clean_text(body.get("mode"), 10)
    phase = clean_text(body.get("phase"), 10)
    if kind not in KINDS or mode not in MODES or phase not in PHASES:
        return None
    raw = body.get("players")
    players = [p for p in (clean_player(x) for x in (raw if isinstance(raw, list) else [])[:8]) if p]
    return {
        "kind": kind,
        "mode": mode,
        "phase": phase,
        "round": clean_int(body.get("round"), 0, 10_000),
        "turn": clean_text(body.get("turn"), 18) or None,
        "winner": clean_text(body.get("winner"), 18) or None,
        "maxSeats": clean_int(body.get("maxSeats"), 2, 8),
        "epoch": clean_int(body.get("epoch"), 0, 100),
        "device": "mobile" if body.get("device") == "mobile" else "desktop",
        "lang": clean_text(body.get("lang"), 16),
        "players": players,
    }


def humans(players: list[dict]) -> list[dict]:
    return [p for p in players if not p["bot"]]


def roster(players: list[dict]) -> list[dict]:
    """The part of a seat worth writing down in the history."""
    return [{"name": p["name"], "bot": p["bot"]} for p in players]


def _day_file(t: float) -> str:
    return os.path.join(STATE_DIR, f"events-{datetime.fromtimestamp(t, timezone.utc):%Y-%m-%d}.jsonl")


def log_event(ev: str, table: dict | None = None, **extra) -> None:
    now = time.time()
    rec: dict = {"t": round(now, 1), "ev": ev}
    if table:
        rec.update({"id": table["id"], "game": table["kind"], "mode": table["mode"]})
    rec.update(extra)
    line = json.dumps(rec, separators=(",", ":")) + "\n"
    with _io_lock:
        try:
            with open(_day_file(now), "a", encoding="utf-8") as fh:
                fh.write(line)
        except OSError:
            pass  # a full disk costs the history, never the directory


def _transitions(old: dict, new: dict) -> None:
    """Write down what changed between two reports of the same table."""
    if old["phase"] != new["phase"]:
        if new["phase"] == "playing":
            new["started"] = time.time()
            log_event("started", new, players=roster(new["players"]))
        elif new["phase"] == "over":
            new["finished"] = time.time()
            log_event("finished", new, winner=new["winner"], rounds=new["round"],
                      secs=int(new["finished"] - (new.get("started") or new["opened"])),
                      players=roster(new["players"]))
        elif new["phase"] == "lobby" and old["phase"] == "over":
            new["started"] = new["finished"] = None
            log_event("rematch", new)

    before = {p["id"]: p for p in humans(old["players"])}
    after = {p["id"]: p for p in humans(new["players"])}
    for pid, p in after.items():
        if pid not in before:
            log_event("joined", new, name=p["name"])
        elif before[pid]["connected"] and not p["connected"]:
            log_event("dropped", new, name=p["name"])
        elif not before[pid]["connected"] and p["connected"]:
            log_event("returned", new, name=p["name"])
    for pid, p in before.items():
        if pid not in after:
            log_event("left", new, name=p["name"])
    if old["mode"] != new["mode"]:
        log_event("listed" if new["mode"] == "public" else "unlisted", new)


def accept_report(table_id: str, report: dict) -> tuple[int, dict]:
    global _dirty
    now = time.time()
    old = _tables.get(table_id)
    if old and now - old["seen"] < REPORT_MIN_GAP:
        # Keep the latest shape without spending a write on it.
        old["pending"] = report
        return 200, {"ok": True}

    if old is None:
        if len(_tables) >= MAX_TABLES:
            return 503, {"error": "too many tables"}
        revived = next((r for r in _recent if r["id"] == table_id
                        and now - r["ended"] < REVIVE_WINDOW), None)
        if revived:
            _recent.remove(revived)
            old = {k: v for k, v in revived.items() if k not in ("ended", "end_reason")}
            log_event("resumed", old, away=int(now - revived["ended"]))

    table = {
        "id": table_id,
        **report,
        "opened": old["opened"] if old else now,
        "started": old.get("started") if old else None,
        "finished": old.get("finished") if old else None,
        "seen": now,
        "reports": (old.get("reports", 0) if old else 0) + 1,
        "peak_humans": max(len(humans(report["players"])), old.get("peak_humans", 0) if old else 0),
    }
    if old is None:
        if table["phase"] == "playing":
            table["started"] = now
        log_event("opened", table, players=roster(table["players"]), device=table["device"])
    else:
        _transitions(old, table)
    _tables[table_id] = table
    _dirty = True
    return 200, {"ok": True, "ttl": int(TABLE_TTL)}


def end_table(table_id: str, reason: str) -> None:
    global _dirty
    table = _tables.pop(table_id, None)
    if not table:
        return
    table.pop("pending", None)
    now = time.time()
    table["ended"] = now
    table["end_reason"] = reason
    log_event("closed", table, reason=reason, secs=int(now - table["opened"]),
              phase=table["phase"], players=roster(table["players"]))
    _recent.insert(0, table)
    del _recent[RECENT_KEEP:]
    _dirty = True


def write_state() -> None:
    now = time.time()
    data = {
        "generated": now,
        "table_ttl": TABLE_TTL,
        "live": sorted(_tables.values(), key=lambda t: -t["opened"]),
        "recent": _recent[:RECENT_KEEP],
        "rooms": live_rooms(),
    }
    tmp = os.path.join(STATE_DIR, "tables.json.tmp")
    with _io_lock:
        try:
            with open(tmp, "w", encoding="utf-8") as fh:
                json.dump(data, fh, separators=(",", ":"))
            os.replace(tmp, os.path.join(STATE_DIR, "tables.json"))
        except OSError:
            pass


def load_state() -> None:
    """Pick the history back up after a restart. Tables that were live come
    back live, and fall quiet in the normal way if nobody is still there."""
    try:
        with open(os.path.join(STATE_DIR, "tables.json"), encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return
    for t in data.get("live", []):
        if isinstance(t, dict) and TABLE_RE.fullmatch(str(t.get("id", ""))):
            _tables[t["id"]] = t
    _recent.extend(r for r in data.get("recent", []) if isinstance(r, dict) and r.get("id"))


def prune_files() -> None:
    cutoff = time.time() - RETAIN_DAYS * 86400
    try:
        names = os.listdir(STATE_DIR)
    except OSError:
        return
    for name in names:
        m = re.fullmatch(r"events-(\d{4}-\d{2}-\d{2})\.jsonl", name)
        if not m:
            continue
        day = datetime.strptime(m.group(1), "%Y-%m-%d").replace(tzinfo=timezone.utc).timestamp()
        if day < cutoff:
            try:
                os.remove(os.path.join(STATE_DIR, name))
            except OSError:
                pass


def housekeeping() -> None:
    global _dirty
    last_write = last_sample = last_prune = 0.0
    while True:
        time.sleep(1.0)
        now = time.time()
        with _lock:
            # Fold in reports that arrived inside the per-table gap.
            for tid, t in list(_tables.items()):
                if "pending" in t and now - t["seen"] >= REPORT_MIN_GAP:
                    accept_report(tid, t.pop("pending"))
            for tid, t in list(_tables.items()):
                if now - t["seen"] > TABLE_TTL:
                    end_table(tid, "went quiet")
            if now - last_sample >= SAMPLE_EVERY:
                last_sample = now
                live = list(_tables.values())
                log_event(
                    "sample",
                    tables=len(live),
                    playing=sum(1 for t in live if t["phase"] == "playing"),
                    humans=sum(sum(1 for p in humans(t["players"]) if p["connected"]) for t in live),
                    bots=sum(sum(1 for p in t["players"] if p["bot"]) for t in live),
                    public_rooms=len(live_rooms()),
                )
            if _dirty or now - last_write >= WRITE_EVERY * 3:
                if now - last_write >= WRITE_EVERY or not last_write:
                    write_state()
                    _dirty = False
                    last_write = now
        if now - last_prune > 3600:
            last_prune = now
            prune_files()


# ------------------------------------------------------------------ http --

class Handler(BaseHTTPRequestHandler):
    server_version = "lobbies/2"

    # -- plumbing ----------------------------------------------------------
    def _cors(self):
        # The game is served from the droplet (under both of its domains) and
        # GitHub Pages, and all of them should be able to see the same list.
        origin = self.headers.get("Origin", "")
        if re.fullmatch(r"https://(aytingchi\.uz|www\.aytingchi\.uz|partyhall\.io|www\.partyhall\.io"
                        r"|[a-z0-9-]+\.github\.io)"
                        r"|http://localhost:\d+", origin or ""):
            self.send_header("Access-Control-Allow-Origin", origin)
            self.send_header("Vary", "Origin")

    def _send(self, code: int, payload: object):
        body = json.dumps(payload).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self._cors()
        self.end_headers()
        self.wfile.write(body)

    @property
    def client_ip(self) -> str:
        # nginx is the only thing in front of this, and it sets this header.
        return (self.headers.get("X-Real-IP") or self.client_address[0] or "?")[:45]

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.send_header("Access-Control-Max-Age", "600")
        self._cors()
        self.end_headers()

    # -- routes ------------------------------------------------------------
    def do_GET(self):
        if self.path.rstrip("/").endswith("/rooms"):
            with _lock:
                return self._send(200, {"rooms": live_rooms()})
        return self._send(404, {"error": "not found"})

    def do_POST(self):
        path = self.path.rstrip("/")
        length = min(int(self.headers.get("Content-Length") or 0), 8192)
        try:
            body = json.loads(self.rfile.read(length) or b"{}")
        except Exception:
            return self._send(400, {"error": "bad json"})
        if not isinstance(body, dict):
            return self._send(400, {"error": "bad body"})

        if path.endswith("/report/close") or path.endswith("/report"):
            return self._report(path, body)

        room_id = clean_text(body.get("id"), 40).upper()
        if not ROOM_RE.fullmatch(room_id):
            return self._send(400, {"error": "bad room id"})

        if path.endswith("/close"):
            with _lock:
                _rooms.pop(room_id, None)
            return self._send(200, {"ok": True})

        if not path.endswith("/announce"):
            return self._send(404, {"error": "not found"})

        ip = self.client_ip
        with _lock:
            limited = not rate_ok("announce*", GLOBAL_ANNOUNCE_PER_MIN) if is_loopback(ip) \
                else not rate_ok(ip, ANNOUNCE_PER_MIN)
            if limited:
                return self._send(429, {"error": "slow down"})

            if room_closed(room_id):
                # Closed by the operator: off the list for a day, and the host
                # is told so it stops beating instead of re-creating it.
                _rooms.pop(room_id, None)
                return self._send(200, {"ok": True, "closed": True})
            host_name = clean_text(body.get("host"), 18) or "Someone"
            if name_banned(host_name):
                # A banned host never reaches the public list. 200, not an
                # error: the client acts on the flag, it does not retry.
                _rooms.pop(room_id, None)
                return self._send(200, {"ok": True, "banned": True})

            existing = _rooms.get(room_id)
            if existing is not None and time.time() - existing["opened"] > MAX_AGE:
                # A room past the age cap is not renewed: tell the host it
                # expired so it stops beating instead of re-creating it.
                _rooms.pop(room_id, None)
                return self._send(200, {"ok": True, "expired": True})
            if existing is None:
                if len(_rooms) >= MAX_ROOMS:
                    return self._send(503, {"error": "directory full"})
                mine = sum(1 for r in _rooms.values() if r["ip"] == ip)
                if not is_loopback(ip) and mine >= MAX_PER_IP:
                    return self._send(429, {"error": "too many rooms"})

            try:
                seats = max(0, min(8, int(body.get("seats", 0))))
                max_seats = max(2, min(8, int(body.get("maxSeats", 6))))
                deviations = max(0, min(30, int(body.get("deviations", 0))))
                # A game already under way stays listed while it has bots a
                # signed-in player could take over.
                in_progress = body.get("inProgress") is True
                open_seats = max(0, min(8, int(body.get("openSeats", 0)))) if in_progress else 0
                round_ = max(0, min(9999, int(body.get("round", 0)))) if in_progress else 0
            except (TypeError, ValueError):
                return self._send(400, {"error": "bad numbers"})

            preset = clean_text(body.get("preset"), 12).lower()
            if preset not in PRESETS:
                preset = "custom"

            now = time.time()
            _rooms[room_id] = {
                "id": room_id,
                "host": host_name,
                "seats": seats,
                "maxSeats": max_seats,
                "preset": preset,
                "deviations": deviations,
                "inProgress": in_progress,
                "openSeats": open_seats,
                "round": round_,
                "ip": ip,
                "seen": now,
                "opened": existing["opened"] if existing else now,
            }
        return self._send(200, {"ok": True, "ttl": int(TTL)})

    def _report(self, path: str, body: dict):
        table_id = clean_text(body.get("id"), 40).upper()
        if not TABLE_RE.fullmatch(table_id):
            return self._send(400, {"error": "bad table id"})
        with _lock:
            if path.endswith("/close"):
                end_table(table_id, "left")
                return self._send(200, {"ok": True})
            if not rate_ok("report*", GLOBAL_REPORTS_PER_MIN):
                return self._send(429, {"error": "slow down"})
            report = clean_report(body)
            if report is None:
                return self._send(400, {"error": "bad report"})
            code, payload = accept_report(table_id, report)
            # The report is kept either way (the panel must stay able to see
            # the table); what moderation adds is instructions in the answer.
            note = moderation_for(table_id, report)
            if note:
                payload.update(note)
                table = _tables.get(table_id)
                sig = json.dumps(note, sort_keys=True)
                if table is not None and table.get("moderation") != sig:
                    table["moderation"] = sig
                    log_event("moderated", table, **note)
        return self._send(code, payload)

    def log_message(self, *_):
        pass


if __name__ == "__main__":
    os.makedirs(STATE_DIR, exist_ok=True)
    load_state()
    threading.Thread(target=housekeeping, daemon=True).start()
    ThreadingHTTPServer.allow_reuse_address = True
    ThreadingHTTPServer((HOST, PORT), Handler).serve_forever()
